### ISSUE TITLE
Nested list produces incorrect markdown

### ISSUE THREAD

**Issue by icanzilb** [MarkCodable/MarkCodable#19]
```swift
struct LL: Codable {
    var list: [[Int]]
}

let ll = LL(list: [[1], [2]])
print(try MarkEncoder().encode(ll))
```

|list|
|----|
|2   |

**Comment by DivineDominion** [comment]
I wanted to go into that direction with the `AnimalFarm` as well. 

Honestly, this eventually gets weirdly out of hand, and a one-dimensional row representation cannot handle this anymore. 

The approach to encode arrays of primitive values virtually as CSV is a good idea. That gives you a comma-separated list of values inside a pipe-separated list of properties, so to speak. The table as a whole is already three-dimensional at that point. But that's likely all that's technically feasible _and_ human readable.

Maybe a sane approach would be to not support arrays of non-"primites" (initially) at all.

Possible enhancement and exception: support for e.g. `[[Int]]`. Looks like cells could get ugly, but a string representation like `[1, 2], [3, 4]` inside a  cell could still be workable. -- I'd suggest to consider this an absolute stretch goal, though, if MarkCodable is for humans first, machines second. If someone needs arrays of objects with dictionaries of more objects inside, by all means use JSON, YAML, or a Plist :)

**Comment by icanzilb** [comment]
@DivineDominion I think it's clear that the markdown format will not support any possible nested structure the way that a JSON file would. Especially, given that the human interaction is a very big priority for this library which additionally shrinks down the possible representation of nested values. 

This biggest issue I have with this issue is that encoding of `[[Int]]` and `[Int]` produces the same result which means a roundtrip of encoding/decoding will decode incorrectly. I'd rather the encoder throws or fatal errors instead.
