### ISSUE TITLE
Split the current unit tests file into smaller chunks

### ISSUE THREAD

**Issue by icanzilb** [MarkCodable/MarkCodable#38]
Ideally we'd split MarkCoderTests.swift into several smaller unit test files.

We should try to identify topics and split the test according to these topics into smaller files such that if a developer is looking for a certain unit test they have a path to reason where to look for it.

**Comment by EmptySet-Exe** [comment]
Would be alright that I contribute to this issue?

**Comment by icanzilb** [comment]
Fixed in https://github.com/MarkCodable/MarkCodable/pull/48
